apiVersion: v1
kind: Service
metadata:
  name: java
  labels:
    app: java
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: java
  type: LoadBalancer